controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_position_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"

    forward_effort_controller:
      type: forward_command_controller/ForwardCommandController


forward_effort_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - joint1
    interface_name: effort


joint_trajectory_position_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - joint1
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    allow_integration_in_goal_trajectories: true
    gains:
      joint1:
        d: 2.0
        ff_velocity_scale: 0.0
        i: 0.5
        i_clamp: 2.0
        p: 2.0