controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gm6020_controller:
      type: pid_controller/PidController

gm6020_controller:
  ros__parameters:
    dof_names: ["yaw"]                                        # Specifies dof_names or axes used by the controller.
    command_interface: "position"                              # Name of the interface used by the controller for writing commands to the hardware.
    reference_and_state_interfaces: ["position", "velocity"]  # Name of the interfaces used by the controller getting hardware states and reference commands. The second interface should be the derivative of the first.
    gains.yaw.p: 1.0
    gains.yaw.i: 1.0
    gains.yaw.d: 1.0
    gains.yaw.antiwindup: false
    gains.yaw.i_clamp_max: 0.0        # Upper integral clamp. Only used if antiwindup is activated.
    gains.yaw.i_clamp_min: 0.0        # Lower integral clamp. Only used if antiwindup is activated.
    gains.yaw.feedforward_gain: 1.0   # Gain for the feed-forward part.
    gains.yaw.angle_wraparound: true  # For joints that wrap around (i.e., are continuous). Normalizes position-error to -pi to pi.
